### PR TITLE
change to fix nullpointerexception

### PR DESCRIPTION
**Pull request by bastyle**
Changes to fix nullpointer when the xml file has different format.
Also i optimized some sentences.
```
 <select 
        id="findAll" 
        parameterType="java.util.HashMap" 
        resultType="cl.cns.serviceregistrarionservice.serviceregistrationserver.InfoServices">
        SELECT * FROM SERVICES
    </select>
```

### CODE REVIEW

**Comment by donhui** [comment]
@bbasstyle Thanks for your PR.

**Comment by donhui** [comment]
I noticed that your git config is not correct just now, I will correct it .
Thanks for your contribution again.

**Comment by bastyle** [comment]
> I noticed that your git config is not correct just now, I will correct it .
> Thanks for your contribution again.

Ok @donhui  can you tell me about this problem to fix it please.

**Comment by donhui** [comment]
I will use `git rebase` to change the author of your commit and then use `git push -f ` to push the code to GitHub repository.

**Comment by donhui** [comment]
@bbasstyle 
before:
image
aftter:
image

**Comment by bastyle** [comment]
> 
> 
> @bbasstyle
> before:
> image
> aftter:
> image

Great. thanks.

**Pull request merged**
